name: distrobuilder
base: core18
version: "1.2"
grade: stable
summary: System container image builder for LXC and LXD
description: |-
  Distrobuilder is a tool which lets you create container images for LXC and LXD.
license: Apache-2.0
confinement: classic

apps:
  distrobuilder:
    command: bin/distrobuilder

parts:
  distrobuilder:
    source: https://github.com/lxc/distrobuilder
    source-type: git
    source-tag: distrobuilder-1.2
    build-packages:
      - gcc
    stage-packages:
      - debootstrap
      - gpg
      - rsync
      - squashfs-tools
    plugin: go
    go-importpath: github.com/lxc/distrobuilder
