name: distrobuilder
base: core22
version: "3.0"
grade: stable
summary: System container and VM image builder for LXC and Incus
description: |-
  Distrobuilder is a tool which lets you create container and VM images for LXC and Incus.
license: Apache-2.0
confinement: classic

apps:
  distrobuilder:
    command: bin/distrobuilder

parts:
  distrobuilder:
    source: https://github.com/lxc/distrobuilder
    source-type: git
    build-attributes:
      - enable-patchelf
    source-tag: distrobuilder-3.0
    build-packages:
      - gcc
    build-snaps:
      - go
    plugin: go
